### ISSUE TITLE
Invalid status code: undefined

### ISSUE THREAD

**Issue by marcoscaceres** [marcoscaceres/respec.org#137]
```
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:249:11)
    at ServerResponse.writeHead (/home/dh_ie5g4j/respec.org/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/home/dh_ie5g4j/respec.org/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/home/dh_ie5g4j/respec.org/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:240:8)
    at ServerResponse.end (/home/dh_ie5g4j/respec.org/node_modules/compression/index.js:103:14)
    at ServerResponse.send (/home/dh_ie5g4j/respec.org/node_modules/express/lib/response.js:221:10)
    at route (/home/dh_ie5g4j/respec.org/routes/w3c/group.js:65:28)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

at:
```JS
    res.json(groupInfo);
  } catch (error) {
    const { statusCode, message } = error;
    res.set("Content-Type", "text/plain");
>>  res.status(statusCode).send(message);
  }
};
```

**Comment by marcoscaceres** [comment]
Closing as resolved — the error handler in `routes/w3c/group.ts:68` already defaults `statusCode` to 500:
```typescript
const { statusCode = 500, message } = error;
```
This prevents the `ERR_HTTP_INVALID_STATUS_CODE` crash when the caught error doesn't have a statusCode property.
