### ISSUE TITLE
Cannot read property 'padStart' of undefined

### ISSUE THREAD

**Issue by marcoscaceres** [marcoscaceres/respec.org#138]
```
TypeError: Cannot read property 'padStart' of undefined
    at formatter (/home/dh_ie5g4j/respec.org/utils/logging.js:76:27)
    at Array.logRequest (/home/dh_ie5g4j/respec.org/node_modules/morgan/index.js:122:18)
    at listener (/home/dh_ie5g4j/respec.org/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/dh_ie5g4j/respec.org/node_modules/on-finished/index.js:100:5)
    at callback (/home/dh_ie5g4j/respec.org/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/home/dh_ie5g4j/respec.org/node_modules/ee-first/index.js:93:5)
    at Socket.emit (events.js:327:22)
    at TCP. (net.js:670:12)
```

At:
```JS
  const unknown = chalk.dim.gray("-");

  return [
    chalk.gray(date),
>>  chalk.gray(remoteAddr.padStart(15)),
    request,
    referrer ? formattedReferrer : unknown,
    contentLength ? chalk.cyan(prettyBytes(contentLength)) : unknown,
    chalk.cyan(responseTime + " ms"),
```

**Comment by bola182** [comment]
Olá pode me ajudar?
Em 27/01/2021 00:25, "Marcos Cáceres" <notifications@github.com> escreveu:

**Comment by sidvishnoi** [comment]
I'm honestly not sure how such inputs happen!
